# Generated by Django 5.2.4 on 2025-07-27 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('jobType', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship'), ('co-op', 'Co-op')], default='', max_length=50)),
                ('location', models.CharField(choices=[('remote', 'Remote'), ('in-person', 'In Person')], default='', max_length=50)),
                ('applicationDeadline', models.DateField()),
                ('description', models.TextField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=12)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('availability_start_date', models.DateField()),
                ('availability_end_date', models.DateField()),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('job_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('inteview', 'Selected for interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobportal.createjob')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
