# Generated by Django 5.2.1 on 2025-09-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(upload_to='media/resumes/'),
        ),
    ]
